properties:
application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  application_uid:
    type: string
    x-google-marketplace:
      type: APPLICATION_UID
  marketplace-hooks.image:
    type: string
    x-google-marketplace:
      type: IMAGE
  marketplace-hooks.service_account:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: Role
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
required:
- name
- namespace
- application_uid
- marketplace-hooks.image
- marketplace-hooks.service_account
