apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-post-delete"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "30"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccount: "{{.Values.service_account}}"
      restartPolicy: Never
      containers:
      - name: post-delete-job
        image: "{{.Values.image}}"
        command:
        - /bin/post-delete.sh
        - --name={{.Release.Name}}
        - --namespace={{.Release.Namespace}}
