apiVersion: v1
appVersion: 0.7.1
description: Marketplace Helm integration
home: https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/
keywords:
- marketplace
- helm
maintainers:
- email: cloud-marketplace-eng@google.copm
  name: google-cloud-marketplace
name: marketplace-k8s-app-tools-helm-hooks
